# Generated by Django 5.0 on 2023-12-24 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_reg_student_ieee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg_Student_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_shirt', models.BooleanField(default=False)),
                ('goodies', models.BooleanField(default=False)),
                ('certificate', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.reg_student')),
            ],
            options={
                'verbose_name': 'Registered Student Item',
            },
        ),
    ]
