# Generated by Django 5.0 on 2023-12-24 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_meeting_session_reg_student_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting_Session_Graphic_Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphic_link', models.URLField(blank=True, max_length=300, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.meeting_session')),
            ],
            options={
                'verbose_name': 'Session Graphic Link',
            },
        ),
        migrations.CreateModel(
            name='Meeting_Session_Graphics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='Meeting Session Graphics/')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.meeting_session')),
            ],
            options={
                'verbose_name': 'Session Graphic Image',
            },
        ),
    ]
