# Generated by Django 5.0 on 2023-12-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_meeting_session_graphic_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting_session_graphic_links',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
