# Generated by Django 5.0 on 2023-12-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_meeting_session_graphic_links_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting_session_graphic_links',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
