# Generated by Django 5.0 on 2023-12-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_meeting_session_graphic_links_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting_session_graphics',
            name='image',
        ),
        migrations.AddField(
            model_name='meeting_session_graphics',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='Meeting Session Graphics/'),
        ),
    ]
