# Generated by Django 5.0 on 2023-12-25 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_meeting_session_graphic_links_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meeting_Session_Graphic_Links',
            new_name='Meeting_Session_FeedBack_Link',
        ),
        migrations.AlterModelOptions(
            name='meeting_session_feedback_link',
            options={'verbose_name': 'Session Feedback Link'},
        ),
    ]
