# Generated by Django 5.0 on 2023-12-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_meeting_session_graphic_links_meeting_session_feedback_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting_session_feedback_link',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
