# Generated by Django 5.0 on 2023-12-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_meeting_session_feedback_link_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting_session_feedback_link',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
