# Generated by Django 5.0 on 2023-12-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_meeting_session_feedback_link_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting_session_feedback_link',
            name='title',
        ),
        migrations.AddField(
            model_name='meeting_session_graphics',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
