# Generated by Django 5.0 on 2023-12-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_meeting_session_feedback_link_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting_session_graphics',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
