# Generated by Django 5.0 on 2023-12-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_meeting_session_graphics_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting_session_graphics',
            options={'verbose_name': 'Session Files'},
        ),
    ]
