# Generated by Django 5.0 on 2023-12-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_meeting_session_graphics_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting_session',
            name='session_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
