# Generated by Django 5.0 on 2023-12-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_meeting_session_session_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting_session_graphics',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='Meeting Session Files/'),
        ),
    ]
