# Generated by Django 5.0 on 2023-12-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_meeting_session_graphics_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meeting_Session_Graphics',
            new_name='Meeting_Session_Files',
        ),
    ]
